### ISSUE TITLE
Lot of dll in ouput dir

### ISSUE THREAD

**Issue by jhdscript** [MartinKuschnik/WmiLight#10]
Hello i m using WmiLight but when i release a dotnet 4.6.2 project in output lots of dll.

How can i prevent this please ?

**Comment by MartinKuschnik** [comment]
Hi,

this is caused by the fact that the 4.6.2 version does not ship all .Net Standard Libs. You can read more about that [here](https://weblog.west-wind.com/posts/2019/Feb/19/Using-NET-Standard-with-Full-Framework-NET).

You could use Version [2.1.17172.10](https://www.nuget.org/packages/WmiLight/2.1.17172.10) of WmiLight. This is not .Net Standard and should not bring this dependencies. But this version will not receive updates in the future.

I think the better option is to update the .Net Framework to 4.8.0

I hope this helps you.
