### ISSUE TITLE
Arrays of IUnknown not working

### ISSUE THREAD

**Issue by jhdscript** [MartinKuschnik/WmiLight#20]
Hello,

i have a wmiobject named "a". When I use a.item("Snapshots") i encountered this exception

![image](https://github.com/user-attachments/assets/f4214095-4186-4688-a42d-3aca4647dc0c)

![image](https://github.com/user-attachments/assets/ad5b739b-873a-4b58-91c6-73c9a8a995f7)

How can acces this property ?

**Comment by MartinKuschnik** [comment]
@jhdscript can you share a bit more code?

**Comment by jhdscript** [comment]
For sure, I loop under all property to get the value but for the propertyname "Snapshots" i encountered the error with  this 3 try

![image](https://github.com/user-attachments/assets/1acfe51b-3b20-4de9-ad99-32e8d916f76b)

**Comment by MartinKuschnik** [comment]
And waht is the wmi query?

**Comment by jhdscript** [comment]
For sure. It's a basic SELECT query on ROOT\virtualization\v2

![image](https://github.com/user-attachments/assets/0700de91-f2d6-4963-bc8b-dc06f030dffa)

**Comment by MartinKuschnik** [comment]
The issue is that you aks for a property that is an array of IUnknown. Im using the [InitVariantFromVariantArrayElem](https://learn.microsoft.com/en-us/windows/win32/api/propvarutil/nf-propvarutil-initvariantfromvariantarrayelem) funtion to initelize the array. But the [InitVariantFromVariantArrayElem](https://learn.microsoft.com/en-us/windows/win32/api/propvarutil/nf-propvarutil-initvariantfromvariantarrayelem) funtion only supports `VT_BSTR`, `VT_BOOL`, `VT_I2`, `VT_I4`, `VT_I8`, `VT_U12`, `VT_U14`, `VT_U18`, `VT_DATE`.

I will implement a sprecial initalization for these cases. 

How urgent is this error?

**Comment by jhdscript** [comment]
This issue drops my code so any fix will be appreciated. Thanx a lot for your work

**Comment by MartinKuschnik** [comment]
@jhdscript Can you please try version 6.2.0 which should be available in a few minutes.

**Comment by MartinKuschnik** [comment]
@jhdscript Works for you?

**Comment by jhdscript** [comment]
Yes thanx a lot
