### ISSUE TITLE
Missing assembly version and strong name signature

### ISSUE THREAD

**Issue by SA5NNN** [MartinKuschnik/WmiLight#6]
Hi,

I just upgraded a project using WmiLight 2.1 to 3.0 and can no longer compile my code since the assembly WmiLight.dll no longer is strong name signed.

I also noticed the lack of assembly metadata such as version.

Is this intended or a regression?

/Nicke

**Comment by MartinKuschnik** [comment]
Hi Nicke,

I removed the strong name because this it makes the dependency managment always hard. Another reason is the switch to another build pipeline because i have to store provide the private key during build.

Do you need the strong naming.

The missing assembly metadata is also caused by the build pipeline switch. I will fix it.

Martin

**Comment by MartinKuschnik** [comment]
[Version 3.0.1](https://www.nuget.org/packages/WmiLight/3.0.1) fixes the missing asembly info.

Providing a package with a singed assembly will need some more time.

**Comment by SA5NNN** [comment]
I can use 2.1 in the meantime. Thanks for the hard work your putting in, it's appreciated!

**Comment by MartinKuschnik** [comment]
Please try [version 3.0.6](https://www.nuget.org/packages/WmiLight/3.0.6) and give me a short feedback if this version workes for you.

**Comment by MartinKuschnik** [comment]
@SA5NNN ???
